version: "3.3"
services:
  db:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
